### ISSUE TITLE
「URLから連続追加」で対応外サービスのURLを追加可能

### ISSUE THREAD

**Issue by moccai** [ihatomorio/arekke#14]
AsIs:
「URLから連続追加」画面にて、対応外サービス（amazon等）のURLを追加することが可能。
追加した場合、トップ画面に追加されるものの題名が「loading」のまま終わらない。

ToBe:
・URLから連続追加時に情報を取得できない場合にエラーを出す

**Comment by ihatomorio** [comment]
URLが未対応であった場合、商品名が「未対応URL」に変化するようにしました。

**Comment by moccai** [comment]
えらい！
